### ISSUE TITLE
Pr Download manager ra rebuild pannunga pa konjam use agum

### ISSUE THREAD

**Issue by sarankumar-ns** [tamdevs/android#1]

**Comment by sarankumar-ns** [comment]
First atha kotlin ku convert pannalaam...
and target 26 to 32 set pannalaam...

**Comment by poovarasan96** [comment]
Kotlin and java kum serthu pannanum bro

**Comment by sarankumar-ns** [comment]
Library thana bro athu ethukku 2 language.
Onnula panna 2 mea use pannikalaamea...

**Comment by poovarasan96** [comment]
Sari ok bro

**Comment by sarankumar-ns** [comment]
Already threading related ah athula irukuratha namma coroutine ku maathalaam...

**Comment by poovarasan96** [comment]
🧐🧐onnum puriyala ye

**Comment by jayakumar143** [comment]
Fork Pannuga bro @sarankumar-ns

**Comment by sarankumar-ns** [comment]
> Fork Pannuga bro @sarankumar-ns

Bro, neenga romba slow poonga...

**Comment by sarankumar-ns** [comment]
downloader branch create pannirukkan bro...

**Comment by sarankumar-ns** [comment]
Sila To-Do project backlog la irukku... Vera iruntha Add pannirunga....

**Comment by jayakumar143** [comment]
😬Apdiya

**Comment by jayakumar143** [comment]
> downloader branch create pannirukkan bro...

Enga bro Enaku kaatala

**Comment by sarankumar-ns** [comment]
downloader nu branch create pannirukkan bro.

**Comment by jayakumar143** [comment]
Got it bro Naa Thani repo nu nenachiten ippotha paathen Branch👍🏻

**Comment by sarankumar-ns** [comment]
Ama bro android ellamea orea repo la vachirupoom...
Like Firebase and Flutter Packages maathiri...

Mudincha Firebase BoM maathiri setup pannalaam...

**Comment by jayakumar143** [comment]
Matha Developers puriyuma... Avanga Clone panni Work panni PR kudupangala

**Comment by sarankumar-ns** [comment]
Ama bro... But ella library um thani thani folder la thana irukkum...

**Comment by sarankumar-ns** [comment]
Naan ithula v1ku oru sila issue pooturukkan...
Intha commit ah naan test panni paakala compose ku change pannitu test pannalamnu irunthan...
So, itha `0.0.1-alpha01` apdi release pannalamaa...

**Comment by sarankumar-ns** [comment]
Version 2 la `Coroutines` and `Workmanager` use pannalaam...

**Comment by sarankumar-ns** [comment]
@jayakumar143 slack workspace onnu create pannirungalean... ithula discussion avlo nalla illa...

**Comment by jayakumar143** [comment]
> Ama bro... But ella library um thani thani folder la thana irukkum...

Ok Understood Matha Devs ku Naamatha Explain panni Sollanum Oru Naal

**Comment by jayakumar143** [comment]
> Naan ithula v1ku oru sila issue pooturukkan...
> Intha commit ah naan test panni paakala compose ku change pannitu test pannalamnu irunthan...
> So, itha `0.0.1-alpha01` apdi release pannalamaa...

Haan Pannuga Naa innum Intha repo Clone pannala Naa Run Pannitu soldren neenga Release Pannuga

**Comment by jayakumar143** [comment]
> @jayakumar143 slack workspace onnu create pannirungalean... ithula discussion avlo nalla illa...

🙂 bro First Ithala pannuvom Devs ellarum Adopt aagatum then Matha app la povom... Ithala notification varamaatinthu

**Comment by sarankumar-ns** [comment]
> > Ama bro... But ella library um thani thani folder la thana irukkum...
> 
> Ok Understood Matha Devs ku Naamatha Explain panni Sollanum Oru Naal

Yes bro... Documentation eluthanum... and Wiki page la kuda poodalaam...

**Comment by jayakumar143** [comment]
> > > Ama bro... But ella library um thani thani folder la thana irukkum...
> > 
> > Ok Understood Matha Devs ku Naamatha Explain panni Sollanum Oru Naal
> 
> Yes bro... Documentation eluthanum... and Wiki page la kuda poodalaam...

Ivlo Speed ah irukinga🤧

**Comment by sarankumar-ns** [comment]
> Ithala notification varamaatinthu

Yes athan probleam... Slack na romba convenient ah irukkum

**Comment by sarankumar-ns** [comment]
> Ivlo Speed ah irukinga🤧
Aalukku ovoru work panna correct ah vanthurum

**Comment by sarankumar-ns** [comment]
Next commit adutha sunday irukkum bro.
Intha weekend la intha maathiri setup ellam panniruvoom...
Sunday Audio discussion vaikalaam...

**Comment by jayakumar143** [comment]
> Next commit adutha sunday irukkum bro.
> Intha weekend la intha maathiri setup ellam panniruvoom...
> Sunday Audio discussion vaikalaam...

Sure Bro Sunday Discuss pannalam Veedu work poitu iruku athan Konjam busy

**Comment by sarankumar-ns** [comment]
The initial version was published, guys.
Checkout at https://jitpack.io/#tamdevs/android/0.0.1
