### ISSUE TITLE
How to Add this project to the Android Studio

### ISSUE THREAD

**Issue by jayakumar143** [TamDevs/android#5]
Antha Example folder ethuku bro

**Comment by jayakumar143** [comment]
A problem occurred evaluating root project 'downloader'.
> Plugin with id 'com.android.library' not found.

intha Error Varutu

**Comment by sarankumar-ns** [comment]
example project thana run panninga...

**Comment by jayakumar143** [comment]
> example project thana run panninga...

Illa Downloader folder pannen

**Comment by jayakumar143** [comment]
> example project thana run panninga...

Illa Downloader folder pannen

**Comment by sarankumar-ns** [comment]
Example folder ah open panni paarunga... atha use panni than work panna vendi irukkum...
